# traefik/traefik.yml
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dashboard:
    address: ":8080"

api:
  dashboard: true

providers:
  kubernetesCRD: {}
  kubernetesIngress: {}
