# config.yaml
services: all

authenticate_service_url: https://authenticate.localhost.pomerium.io

shared_secret: "TdSgecryjMIQc+mtD1lNRP7QPES0nOz/NcVQUD2xF4Y="
cookie_secret: "TdSgecryjMIQc+mtD1lNRP7QPES0nOz/NcVQUD2xF4Y="

idp_provider: oidc
idp_client_id: 'admin_chatbot_client_dev'
idp_client_secret: '4m9y58q8XmkDifM16eyT9S3KPDUZRi5A' # Replace with the actual secret
idp_provider_url: 'https://auth.alfinac.com:5002/realms/admin_chatbot'
signing_key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVA2TUN5UFI5OUNmSEVkU0s4cVdzbk51Q0RyMVZ3ay93RER1RVhyQitELzZvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQ0JTK3gyQnJRNVJqNHJFcU5PSEVsUFVESXJiRlNhRitoWEhEL1RYby9rQWVKU1lJSjJHVwpZMnE0a0NPNTU4RmdoYmxDTUplYVdjV1luT3JuZkpxeXRnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
tls_insecure_skip_verify: true

routes:
  - from: https://verify.localhost.pomerium.io
    to: http://verify:8000
    allow_any_authenticated_user: true
    pass_identity_headers: true
    insecure_skip_verify_tls: true
#    pass_identity_headers: true
#    policy:
#      allow:
#        or:
#          - domain:
#              is: alfinac.com
#          - email:
#              is: huy.trannguyenhoang7@gmail.com
#          - user:
#              is: bd9d7340-1c27-4d87-b3e0-fad7ec753888

  - from: https://grafana.localhost.pomerium.io
    to: http://grafana:3000
    allow_any_authenticated_user: true
    pass_identity_headers: true
#    pass_identity_headers: true
#    jwt_claims_headers: true
#    policy:
#      allow:
#        or:
#          - domain:
#              is: alfinac.com
#          - email:
#              is: huy.trannguyenhoang7@gmail.com
#          - user:
#              is: bd9d7340-1c27-4d87-b3e0-fad7ec753888
