version: "3"

services:
  pomerium:
    image: pomerium/pomerium:latest
    ports:
      - "443:443"
    volumes:
      - ./config.yaml:/pomerium/config.yaml:ro
    environment:
      - POMERIUM_CONFIG=/pomerium/config.yaml
    restart: always
    networks:
      - pomnet

  verify:
    image: pomerium/verify:latest
    environment:
      JWKS_ENDPOINT: https://pomerium/.well-known/pomerium/jwks.json
    networks:
      - pomnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - pomnet

volumes:
  grafana-storage:

networks:
  pomnet: