log:
  level: DEBUG

accessLog: { }

api:
  insecure: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  admin:
    address: ":8082"
providers:
  docker:
    exposedByDefault: false

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

  consulCatalog:
    endpoint:
      address: "consul-discovery:8500"
    prefix: "traefik"
    exposedByDefault: true
