log:
  level: DEBUG

accessLog: {}

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/local.crt"
        keyFile: "/certs/local.key"

providers:
  docker:
    exposedByDefault: false


  consulCatalog:
    endpoint:
      address: "consul-discovery:8500"
    prefix: "traefik"
    exposedByDefault: true