log:
  level: DEBUG

accessLog: {}

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

  file:
    directory: "/etc/traefik/dynamic"
    watch: true

  consulCatalog:
    endpoint:
      address: "consul-discovery:8500"
    prefix: "traefik"
    exposedByDefault: true
